### ISSUE TITLE
View Timeline does not work with `animation-time-range: entry;` or `exit`

### ISSUE THREAD

**Issue by AdaRoseCannon** [flackr/scroll-timeline#107]
Safari doesn't throw an error but it just doesn't do anything.

Chrome, throws an Error and a lot of the values in the timing object are `NaN`

```
Uncaught TypeError: Failed to execute 'updateTiming' on 'AnimationEffect': Failed to read the 'delay' property from 'OptionalEffectTiming': The provided double value is non-finite.
    at Object.apply (proxy-animation.js:708:30)
    at proxy-animation.js:105:39
    at F (proxy-animation.js:370:18)
    at W (proxy-animation.js:91:24)
    at z (proxy-animation.js:262:24)
    at e.get (proxy-animation.js:1094:36)
    at e.get (proxy-animation.js:1172:56)
    at B (proxy-animation.js:447:20)
    at n.play (proxy-animation.js:1306:5)
    at scroll-timeline-css.js:178:24
```

**Comment by bramus** [comment]
The CSS property to use is `animation-range`.

Testing the latest version polyfill will this little snippet below _(and variations thereof)_ does not throw any error:

```css
animation: fade-in linear forwards, fade-out linear forwards;
animation-timeline: view();
animation-range: entry, exit;
```

I think this issue may be closed @flackr @kevers-google.
