### ISSUE TITLE
CSS Polyfill conflicts with browsers that have support enabled

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#50]
Trying out https://codepen.io/bramus/pen/popYBRz/19bf451ebc93a14378b4d439124a0d61 in stock Chrome works like a charm. 

Trying the same demo out in a browser with support _(i.e. Chrome with the `--enable-experimental-web-platform-features` flag or Firefox with `layout.css.scroll-linked-animations.enabled` set to `true`)_ doesn't do anything.

I would have expected the polyfill to only do its thing when `@scroll-timeline` is not available.

The easy fix would be to wrap the call to `initCSSPolyfill()` in a `if (!CSS.supports("animation-timeline: works")) { … }` block.

**Comment by bramus** [comment]
Did a quick workaround in #51, but perhaps this isn’t the way to go.

Digging deeper into the demo [when viewed in a non-iframed/standalone window](https://cdpn.io/pen/debug/popYBRz/19bf451ebc93a14378b4d439124a0d61) _(i.e. without the CodePen chrome)_, I find this error in the console:

```
proxy-animation.js:571 Uncaught DOMException: Failed to set the 'currentTime' property on 'Animation': Invalid currentTime. Setting currentTime using absolute time values is not supported for progress based animations.
    at e.F (https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:12240)
    at f (https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:4171)
    at y (https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:5509)
    at W (https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:11806)
    at n.play (https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:14354)
    at https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:31487
    at Array.forEach (<anonymous>)
    at https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:30354
```

**Comment by flackr** [comment]
Note also issue #4. I think we should skip both the CSS and JS polyfills when native support exists.
